### PR TITLE
version update

### PR DESCRIPTION
**Pull request by tsenapathi**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tsenapathi** [comment]
@chrisbarnettster getting an error `UnsupportedPythonVersion: Package 'propka' requires a different Python: 2.7.15 not in '>=3.6'` but this package is compatible with python >=3.6. Any ideas?

**Comment by chrisbarnettster** [comment]
@tsenapathi In the pipeline log you'll see there is an attempt at building a Python 2 version (see below). So the error is then that Python 2.7.15 doesn't meet the requirement that you must have Python >=3.6. 

`The following NEW packages will be INSTALLED:
......
......
    python:           2.7.15-h5a48372_1011_cpython conda-forge
`

Why is this script trying to build a conda package for Python 2.7 in addition to Python 3 (possibly because the pip wheel says its supports both)? Can you update the build script to only build for Python 3.

**Comment by chrisbarnettster** [comment]
From https://github.com/conda-forge/conda-smithy/issues/1110 and https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#skipping-builds
Try:
`
skip: True  # [py2k]
`

**Comment by tsenapathi** [comment]
@conda-forge-admin, please rerender

**Comment by tsenapathi** [comment]
@sobolevnrm I am updating the version.

**Comment by tsenapathi** [comment]
@chrisbarnettster could you double-check if everything is okay and merge?

**Comment by tsenapathi** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
